apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-config
resources:
  - oidc-secret.yaml
  - oidc-ca.yaml
  - cluster-role-binding.yaml
patches:
  - path: oauth-patch.yaml
    target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
