apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-stack-generator
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: 'https://github.com/IDuenas/OCP_CRC_Private.git'
        revision: HEAD
        directories:
          - path: clusters/crc/services/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/IDuenas/OCP_CRC_Private.git'
        targetRevision: HEAD
        path: '{{path}}'
        kustomize:
          buildOptions: --enable-helm
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
