apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - operator.yaml
  - keycloak-cr.yaml
  - certificate.yaml
  - admin-secret-sealed.yaml
  - db-secret-sealed.yaml
  - realm-secrets-sealed.yaml
  - realm-import.yaml
