apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - operator.yaml
  - keycloak-cr.yaml
  - certificate.yaml
  - admin-secret.yaml
  - db-secret.yaml
  - realm-import.yaml
